[extend]
base = "none"

title = "gitleaks config para lab"

[allowlist]
paths = [
  '''leaks\.tf$'''
]

[[rules]]
id = "aws-access-key"
description = "AWS Access Key"
regex = '''(A3T[A-Z0-9]|AKIA|ASIA|ABIA|ACCA)[A-Z0-9]{16}'''
tags = ["key", "AWS"]

[[rules]]
id = "github-pat"
description = "GitHub PAT"
regex = '''ghp_[0-9a-zA-Z]{36}'''
tags = ["key", "GitHub"]

[[rules]]
id = "generic-password"
description = "Contrase√±a en default Terraform"
regex = '''default\s*=\s*['"][^'"]{8,}['"]'''
tags = ["password", "terraform"]