USER-SUPPLIED VALUES:
driver:
  kind: module
  loader:
    version: 3.0.0
extraVolumeMounts:
- mountPath: /etc/falco/custom_rules
  name: falco-custom-rules
  readOnly: true
extraVolumes:
- configMap:
    name: falco-custom-rules
  name: falco-custom-rules
falco:
  json_include_output_property: true
  json_output: true
  rules_files:
  - /etc/falco/falco_rules.yaml
  - /etc/falco/falco_rules.local.yaml
  - /etc/falco/custom_rules/falco.yaml
falcosidekick:
  config:
    slack:
      minimumpriority: Debug
      webhookurl: https://hooks.slack.com/services/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
  enabled: true
